export const SESSION_COOKIE_NAME = "kv_session";

export const SESSION_DURATION_DAYS = 30;

const SECONDS_PER_DAY = 24 * 60 * 60;

export const SESSION_DURATION_MS = SESSION_DURATION_DAYS * SECONDS_PER_DAY * 1000;

export const SESSION_COOKIE_MAX_AGE_SECONDS = SESSION_DURATION_DAYS * SECONDS_PER_DAY;
